HttpFailedException: рендерить cause-exception
Т.к. на iOS какие-то проблемы в GetIndex, app/config.xml явно добавлен
suggest.cdnvideo.ru без wildcard, но это пальцем в небо.